# Generated by Django 5.0.1 on 2024-03-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_fase_servicio_imagenfase_fase_servicio_detallecita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(through='autenticacion.DetalleCita', to='autenticacion.servicio'),
        ),
    ]
