# Generated by Django 5.0.1 on 2024-03-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_cita_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenfase',
            name='servicio_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.servicio'),
        ),
    ]
