# Generated by Django 5.0.1 on 2024-03-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_imagenfase_servicio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenfase',
            old_name='servicio_id',
            new_name='servicio',
        ),
    ]
