# Generated by Django 5.0.3 on 2024-04-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_remove_imagenfase_imagen_path_imagenfase_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecita',
            name='total',
        ),
    ]
